# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 34eb619cc1fd99294da3c11252512f60b8eb50e3dab67dcd2bda103e7051788ea45ce0be0832bbd5b3cd79c42aad89ce4442c70059712cafb93e04193f079b42

test:
  secret_key_base: d32cc9a3ae075b6e50630d185a1aa1144cfc2cee063fecbea99b960f10bc3266255aa907d6cc4d749b57b2928041ea0c163a1604fe2324f9d44412cf7af40cc5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
